### PR TITLE
PROD-2716: replace succeeded and failed with success and failure

### PR DESCRIPTION
**Pull request by nitishkumar71**
We are standardizing the `event_action` values across different integrations.

### CODE REVIEW

**Review by jossemargt-cto-ai — APPROVED** [review]

**Comment by marcoguillenuio** [comment]
>

**Comment by marcoguillenuio** [comment]
@nitishkumar71 cc @jossemargt-cto-ai 
A general comment about the standardization. Great that we are standardizing, I have seen throughout the code some different event actions / combinations for the same action, it would be good to review the components where these variations are used.

Sorry in first instance I added this comment with the options "Close with comment" 😊

**Comment by nitishkumar71** [comment]
@marcoguillenuio I had looked at the data. We are just updating example.

In the [code](https://github.com/cto-ai/metrics-api/blob/main/migrations/019.do.add-deployment-views.sql#L18-L19) we have been only using succeeded and failed as synonym for success and failure respectively.

We are not planning to remove them. It's more about communicating same thing in all places.

**Review by marcoguillenuio — APPROVED** [review]

**Review by NickAnderegg — APPROVED** [review]
Made a commit with changes for consistency with other readmes. Overall, LGTM.

**Pull request merged**
